





let peoples = [
    { id: 1, name: "John", age: 25, country: "Bangladesh", nationality: "Bangali", blodGroup: "A+" },
    { id: 2, name: "Sarah", age: 30, country: "India", nationality: "Indian", blodGroup: "B+" },
    { id: 3, name: "Michael", age: 28, country: "USA", nationality: "American", blodGroup: "O-" },
    { id: 4, name: "Ayesha", age: 22, country: "Pakistan", nationality: "Pakistani", blodGroup: "AB+" },
    { id: 5, name: "David", age: 35, country: "Canada", nationality: "Canadian", blodGroup: "A-" },
    { id: 6, name: "Maria", age: 26, country: "Brazil", nationality: "Brazilian", blodGroup: "O+" },
    { id: 7, name: "Hiroshi", age: 32, country: "Japan", nationality: "Japanese", blodGroup: "B-" },
    { id: 8, name: "Fatima", age: 24, country: "UAE", nationality: "Emirati", blodGroup: "A+" },
    { id: 9, name: "Liam", age: 29, country: "UK", nationality: "British", blodGroup: "O+" },
    { id: 10, name: "Sophia", age: 27, country: "Australia", nationality: "Australian", blodGroup: "AB-" },
    { id: 11, name: "Noah", age: 23, country: "Germany", nationality: "German", blodGroup: "A+" },
    { id: 12, name: "Emma", age: 31, country: "France", nationality: "French", blodGroup: "B+" },
    { id: 13, name: "Oliver", age: 26, country: "Italy", nationality: "Italian", blodGroup: "O-" },
    { id: 14, name: "Mia", age: 25, country: "Spain", nationality: "Spanish", blodGroup: "AB+" },
    { id: 147, name: "Isabel", age: 24, country: "France", nationality: "French", blodGroup: "A+" },
    { id: 148, name: "Caden", age: 29, country: "Italy", nationality: "Italian", blodGroup: "O-" },
    { id: 149, name: "Hazel", age: 26, country: "Australia", nationality: "Australian", blodGroup: "B+" },
    { id: 150, name: "Levi", age: 31, country: "Japan", nationality: "Japanese", blodGroup: "AB+" },
    { id: 110, name: "Liam", age: 24, country: "Ireland", nationality: "Irish", bloodGroup: "O+" },
    { id: 111, name: "Olivia", age: 29, country: "New Zealand", nationality: "Kiwi", bloodGroup: "A-" },
    { id: 112, name: "Noah", age: 31, country: "Argentina", nationality: "Argentinian", bloodGroup: "B-" },
    { id: 113, name: "Emma", age: 26, country: "Sweden", nationality: "Swedish", bloodGroup: "AB+" },
    { id: 114, name: "Ava", age: 23, country: "Brazil", nationality: "Brazilian", bloodGroup: "A+" },
    { id: 115, name: "Ethan", age: 28, country: "South Africa", nationality: "South African", bloodGroup: "O-" },
    { id: 116, name: "Charlotte", age: 30, country: "Mexico", nationality: "Mexican", bloodGroup: "B+" },
    { id: 117, name: "James", age: 25, country: "Egypt", nationality: "Egyptian", bloodGroup: "AB-" },
    { id: 118, name: "Sophia", age: 27, country: "Poland", nationality: "Polish", bloodGroup: "A+" },
    { id: 119, name: "Benjamin", age: 32, country: "Norway", nationality: "Norwegian", bloodGroup: "O+" },
    { id: 120, name: "Mia", age: 24, country: "Finland", nationality: "Finnish", bloodGroup: "B-" },
    { id: 121, name: "Evelyn", age: 29, country: "Switzerland", nationality: "Swiss", bloodGroup: "AB+" },
    { id: 122, name: "Lucas", age: 31, country: "Denmark", nationality: "Danish", bloodGroup: "A-" },
    { id: 123, name: "Harper", age: 26, country: "Austria", nationality: "Austrian", bloodGroup: "O-" },
    { id: 124, name: "Mason", age: 23, country: "Greece", nationality: "Greek", bloodGroup: "B+" },
    { id: 125, name: "Amelia", age: 28, country: "Portugal", nationality: "Portuguese", bloodGroup: "A+" },
    { id: 126, name: "Jackson", age: 30, country: "Belgium", nationality: "Belgian", bloodGroup: "O+" },
    { id: 127, name: "Ella", age: 25, country: "Netherlands", nationality: "Dutch", bloodGroup: "AB-" },
    { id: 128, name: "Aiden", age: 27, country: "Ireland", nationality: "Irish", bloodGroup: "A-" },
    { id: 129, name: "Abigail", age: 32, country: "New Zealand", nationality: "Kiwi", bloodGroup: "B-" },
    { id: 130, name: "Leo", age: 24, country: "Argentina", nationality: "Argentinian", bloodGroup: "O+" },
    { id: 131, name: "Santo", age: 29, country: "Sweden", nationality: "Swedish", bloodGroup: "A+" },
    { id: 132, name: "Samuel", age: 31, country: "Brazil", nationality: "Brazilian", bloodGroup: "AB+" },
    { id: 133, name: "Sofia", age: 26, country: "South Africa", nationality: "South African", bloodGroup: "B+" },
    { id: 134, name: "Wyatt", age: 23, country: "Mexico", nationality: "Mexican", bloodGroup: "A-" },
    { id: 135, name: "Grace", age: 28, country: "Egypt", nationality: "Egyptian", bloodGroup: "O-" },
    { id: 136, name: "Gabriel", age: 30, country: "Poland", nationality: "Polish", bloodGroup: "O+" },
    { id: 137, name: "Lily", age: 25, country: "Norway", nationality: "Norwegian", bloodGroup: "A+" },
    { id: 138, name: "Michael", age: 27, country: "Finland", nationality: "Finnish", bloodGroup: "AB-" },
    { id: 139, name: "Zoe", age: 32, country: "Switzerland", nationality: "Swiss", bloodGroup: "B-" },
    { id: 140, name: "Jack", age: 24, country: "Denmark", nationality: "Danish", bloodGroup: "O+" },
    { id: 141, name: "Nora", age: 29, country: "Austria", nationality: "Austrian", bloodGroup: "A-" },
    { id: 142, name: "David", age: 31, country: "Greece", nationality: "Greek", bloodGroup: "AB+" },
    { id: 143, name: "Isla", age: 26, country: "Portugal", nationality: "Portuguese", bloodGroup: "B+" },
    { id: 144, name: "Oliver", age: 23, country: "Belgium", nationality: "Belgian", bloodGroup: "A+" },
    { id: 145, name: "Aria", age: 28, country: "Netherlands", nationality: "Dutch", bloodGroup: "O-" },
    { id: 146, name: "Caleb", age: 30, country: "Ireland", nationality: "Irish", bloodGroup: "B-" },
    { id: 147, name: "Scarlett", age: 25, country: "New Zealand", nationality: "Kiwi", bloodGroup: "O+" },
    { id: 148, name: "Henry", age: 27, country: "Argentina", nationality: "Argentinian", bloodGroup: "AB-" },
    { id: 149, name: "Luna", age: 32, country: "Sweden", nationality: "Swedish", bloodGroup: "A-" },
    { id: 150, name: "Christopher", age: 24, country: "Brazil", nationality: "Brazilian", bloodGroup: "B+" },
    { id: 151, name: "Penelope", age: 29, country: "South Africa", nationality: "South African", bloodGroup: "A+" },
    { id: 152, name: "Sebastian", age: 31, country: "Mexico", nationality: "Mexican", bloodGroup: "O+" },
    { id: 153, name: "Victoria", age: 26, country: "Egypt", nationality: "Egyptian", bloodGroup: "AB+" },
    { id: 154, name: "Daniel", age: 23, country: "Poland", nationality: "Polish", bloodGroup: "B-" },
    { id: 155, name: "Hannah", age: 28, country: "Norway", nationality: "Norwegian", bloodGroup: "O-" },
    { id: 156, name: "Mateo", age: 30, country: "Finland", nationality: "Finnish", bloodGroup: "A-" },
    { id: 157, name: "Ellie", age: 25, country: "Switzerland", nationality: "Swiss", bloodGroup: "B+" },
    { id: 158, name: "Joseph", age: 27, country: "Denmark", nationality: "Danish", bloodGroup: "AB-" },
    { id: 159, name: "Aubrey", age: 32, country: "Austria", nationality: "Austrian", bloodGroup: "A+" },
    { id: 160, name: "Andrew", age: 24, country: "Greece", nationality: "Greek", bloodGroup: "O+" },
    { id: 161, name: "Grace", age: 29, country: "Portugal", nationality: "Portuguese", bloodGroup: "A-" },
    { id: 162, name: "Miles", age: 31, country: "Belgium", nationality: "Belgian", bloodGroup: "B-" },
    { id: 163, name: "Bella", age: 26, country: "Netherlands", nationality: "Dutch", bloodGroup: "AB+" },
    { id: 164, name: "Owen", age: 23, country: "Ireland", nationality: "Irish", bloodGroup: "A+" },
    { id: 165, name: "Avery", age: 28, country: "New Zealand", nationality: "Kiwi", bloodGroup: "O-" },
    { id: 166, name: "Nicholas", age: 30, country: "Argentina", nationality: "Argentinian", bloodGroup: "B+" },
    { id: 167, name: "Hazel", age: 25, country: "Sweden", nationality: "Swedish", bloodGroup: "AB-" },
    { id: 168, name: "Luke", age: 27, country: "Brazil", nationality: "Brazilian", bloodGroup: "A+" },
    { id: 169, name: "Zoe", age: 32, country: "South Africa", nationality: "South African", bloodGroup: "O+" },
    { id: 170, name: "Isaac", age: 24, country: "Mexico", nationality: "Mexican", bloodGroup: "B-" },
    { id: 171, name: "Evelyn", age: 29, country: "Egypt", nationality: "Egyptian", bloodGroup: "AB+" },
    { id: 172, name: "Caleb", age: 31, country: "Poland", nationality: "Polish", bloodGroup: "A-" },
    { id: 173, name: "Leah", age: 26, country: "Norway", nationality: "Norwegian", bloodGroup: "O-" },
    { id: 174, name: "Elijah", age: 23, country: "Finland", nationality: "Finnish", bloodGroup: "B+" },
    { id: 175, name: "Addison", age: 28, country: "Switzerland", nationality: "Swiss", bloodGroup: "A+" },
    { id: 176, name: "Alexander", age: 30, country: "Denmark", nationality: "Danish", bloodGroup: "O+" },
    { id: 177, name: "Natalie", age: 25, country: "Austria", nationality: "Austrian", bloodGroup: "AB-" },
    { id: 178, name: "Dylan", age: 27, country: "Greece", nationality: "Greek", bloodGroup: "A-" },
    { id: 179, name: "Savannah", age: 32, country: "Portugal", nationality: "Portuguese", bloodGroup: "B-" },
    { id: 180, name: "Mason", age: 24, country: "Belgium", nationality: "Belgian", bloodGroup: "O+" },
    { id: 181, name: "Chloe", age: 29, country: "Netherlands", nationality: "Dutch", bloodGroup: "A+" },
    { id: 182, name: "Gabriel", age: 31, country: "Ireland", nationality: "Irish", bloodGroup: "AB+" },
    { id: 183, name: "Lillian", age: 26, country: "New Zealand", nationality: "Kiwi", bloodGroup: "B+" },
    { id: 184, name: "Isaac", age: 23, country: "Argentina", nationality: "Argentinian", bloodGroup: "A-" },
    { id: 185, name: "Stella", age: 28, country: "Sweden", nationality: "Swedish", bloodGroup: "O-" },
    { id: 186, name: "Nora", age: 30, country: "Brazil", nationality: "Brazilian", bloodGroup: "B+" },
    { id: 187, name: "Julian", age: 25, country: "South Africa", nationality: "South African", bloodGroup: "AB-" },
    { id: 188, name: "Layla", age: 27, country: "Mexico", nationality: "Mexican", bloodGroup: "A+" },
    { id: 189, name: "Thomas", age: 32, country: "Egypt", nationality: "Egyptian", bloodGroup: "O+" },
    { id: 190, name: "Miles", age: 24, country: "Poland", nationality: "Polish", bloodGroup: "B-" },
    { id: 191, name: "Claire", age: 29, country: "Norway", nationality: "Norwegian", bloodGroup: "AB+" },
    { id: 192, name: "Aaron", age: 31, country: "Finland", nationality: "Finnish", bloodGroup: "A-" },
    { id: 193, name: "Victoria", age: 26, country: "Switzerland", nationality: "Swiss", bloodGroup: "O-" },
    { id: 194, name: "Jackson", age: 23, country: "Denmark", nationality: "Danish", bloodGroup: "B+" },
    { id: 195, name: "Scarlett", age: 28, country: "Austria", nationality: "Austrian", bloodGroup: "A+" },
    { id: 196, name: "Wyatt", age: 30, country: "Greece", nationality: "Greek", bloodGroup: "O+" },
    { id: 197, name: "Penelope", age: 25, country: "Portugal", nationality: "Portuguese", bloodGroup: "AB-" },
    { id: 198, name: "Sebastian", age: 27, country: "Belgium", nationality: "Belgian", bloodGroup: "A-" },
    { id: 199, name: "Lillian", age: 32, country: "Netherlands", nationality: "Dutch", bloodGroup: "B-" },
    { id: 200, name: "David", age: 24, country: "Ireland", nationality: "Irish", bloodGroup: "O+" },
    { id: 201, name: "Chloe", age: 29, country: "New Zealand", nationality: "Kiwi", bloodGroup: "A+" },
    { id: 202, name: "Leo", age: 31, country: "Argentina", nationality: "Argentinian", bloodGroup: "AB+" },
    { id: 203, name: "Addison", age: 26, country: "Sweden", nationality: "Swedish", bloodGroup: "B+" },
    { id: 204, name: "Carter", age: 23, country: "Brazil", nationality: "Brazilian", bloodGroup: "A-" },
    { id: 205, name: "Madison", age: 28, country: "South Africa", nationality: "South African", bloodGroup: "O-" },
    { id: 206, name: "Benjamin", age: 30, country: "Mexico", nationality: "Mexican", bloodGroup: "O+" },
    { id: 207, name: "Nora", age: 25, country: "Egypt", nationality: "Egyptian", bloodGroup: "A+" },
    { id: 208, name: "Santo", age: 27, country: "Poland", nationality: "Polish", bloodGroup: "AB-" },
    { id: 209, name: "Stella", age: 32, country: "Norway", nationality: "Norwegian", bloodGroup: "B-" },
    { id: 210, name: "Lucas", age: 25, country: "Canada", nationality: "Canadian", bloodGroup: "O+" },
    { id: 211, name: "Maya", age: 30, country: "Australia", nationality: "Australian", bloodGroup: "A-" },
    { id: 212, name: "Nathan", age: 28, country: "UK", nationality: "British", bloodGroup: "B-" },
    { id: 213, name: "Chloe", age: 22, country: "USA", nationality: "American", bloodGroup: "AB+" },
    { id: 214, name: "Ethan", age: 35, country: "Germany", nationality: "German", bloodGroup: "A+" },
    { id: 215, name: "Isabella", age: 29, country: "France", nationality: "French", bloodGroup: "O-" },
    { id: 216, name: "Jacob", age: 31, country: "Italy", nationality: "Italian", bloodGroup: "B+" },
    { id: 217, name: "Sophie", age: 26, country: "Spain", nationality: "Spanish", bloodGroup: "AB-" },
    { id: 218, name: "Daniel", age: 33, country: "Japan", nationality: "Japanese", bloodGroup: "A+" },
    { id: 219, name: "Emily", age: 24, country: "China", nationality: "Chinese", bloodGroup: "O+" },
    { id: 220, name: "Matthew", age: 27, country: "India", nationality: "Indian", bloodGroup: "B-" },
    { id: 221, name: "Ava", age: 32, country: "Brazil", nationality: "Brazilian", bloodGroup: "AB+" },
    { id: 222, name: "Alexander", age: 23, country: "Mexico", nationality: "Mexican", bloodGroup: "A-" },
    { id: 223, name: "Olivia", age: 30, country: "Russia", nationality: "Russian", bloodGroup: "O-" },
    { id: 224, name: "William", age: 29, country: "South Africa", nationality: "South African", bloodGroup: "B+" },
    { id: 225, name: "Mia", age: 25, country: "Egypt", nationality: "Egyptian", bloodGroup: "A+" },
    { id: 226, name: "James", age: 34, country: "Turkey", nationality: "Turkish", bloodGroup: "O+" },
    { id: 227, name: "Amelia", age: 28, country: "Sweden", nationality: "Swedish", bloodGroup: "AB-" },
    { id: 228, name: "Leo", age: 30, country: "Norway", nationality: "Norwegian", bloodGroup: "A-" },
    { id: 229, name: "Ella", age: 26, country: "Denmark", nationality: "Danish", bloodGroup: "B-" },
    { id: 230, name: "Benjamin", age: 31, country: "Finland", nationality: "Finnish", bloodGroup: "O+" },
    { id: 231, name: "Sofia", age: 24, country: "Poland", nationality: "Polish", bloodGroup: "A+" },
    { id: 232, name: "Jackson", age: 29, country: "Greece", nationality: "Greek", bloodGroup: "AB+" },
    { id: 233, name: "Grace", age: 27, country: "Portugal", nationality: "Portuguese", bloodGroup: "B+" },
    { id: 234, name: "Caleb", age: 33, country: "Ireland", nationality: "Irish", bloodGroup: "A-" },
    { id: 235, name: "Lily", age: 22, country: "New Zealand", nationality: "Kiwi", bloodGroup: "O-" },
    { id: 236, name: "Logan", age: 28, country: "Argentina", nationality: "Argentinian", bloodGroup: "O+" },
    { id: 237, name: "Hannah", age: 30, country: "Switzerland", nationality: "Swiss", bloodGroup: "AB-" },
    { id: 238, name: "Samuel", age: 25, country: "Belgium", nationality: "Belgian", bloodGroup: "A+" },
    { id: 239, name: "Aria", age: 34, country: "Netherlands", nationality: "Dutch", bloodGroup: "B-" },
    { id: 240, name: "Dylan", age: 29, country: "Austria", nationality: "Austrian", bloodGroup: "O+" },
    { id: 241, name: "Stella", age: 31, country: "Hungary", nationality: "Hungarian", bloodGroup: "A-" },
    { id: 242, name: "Joseph", age: 26, country: "Czech Republic", nationality: "Czech", bloodGroup: "B+" },
    { id: 243, name: "Zoe", age: 32, country: "Israel", nationality: "Israeli", bloodGroup: "AB+" },
    { id: 244, name: "Gabriel", age: 24, country: "UAE", nationality: "Emirati", bloodGroup: "A-" },
    { id: 245, name: "Evelyn", age: 29, country: "Saudi Arabia", nationality: "Saudi", bloodGroup: "O-" },
    { id: 246, name: "Christian", age: 30, country: "Qatar", nationality: "Qatari", bloodGroup: "B+" },
    { id: 247, name: "Bella", age: 25, country: "Kuwait", nationality: "Kuwaiti", bloodGroup: "A+" },
    { id: 248, name: "Miles", age: 33, country: "Oman", nationality: "Omani", bloodGroup: "O+" },
    { id: 249, name: "Avery", age: 28, country: "Bahrain", nationality: "Bahraini", bloodGroup: "AB-" },
    { id: 250, name: "Owen", age: 27, country: "Jordan", nationality: "Jordanian", bloodGroup: "A-" },
    { id: 251, name: "Victoria", age: 32, country: "Lebanon", nationality: "Lebanese", bloodGroup: "B-" },
    { id: 252, name: "Isaac", age: 23, country: "Syria", nationality: "Syrian", bloodGroup: "O+" },
    { id: 253, name: "Penelope", age: 29, country: "Iraq", nationality: "Iraqi", bloodGroup: "A+" },
    { id: 254, name: "Julian", age: 30, country: "Iran", nationality: "Iranian", bloodGroup: "AB+" },
    { id: 255, name: "Layla", age: 26, country: "Afghanistan", nationality: "Afghan", bloodGroup: "B+" },
    { id: 256, name: "Thomas", age: 34, country: "Pakistan", nationality: "Pakistani", bloodGroup: "A-" },
    { id: 257, name: "Natalie", age: 28, country: "Bangladesh", nationality: "Bangladeshi", bloodGroup: "O-" },
    { id: 258, name: "Henry", age: 30, country: "Sri Lanka", nationality: "Sri Lankan", bloodGroup: "O+" },
    { id: 259, name: "Audrey", age: 25, country: "Nepal", nationality: "Nepali", bloodGroup: "AB-" },
    { id: 260, name: "Jack", age: 33, country: "Bhutan", nationality: "Bhutanese", bloodGroup: "A-" },
    { id: 261, name: "Madeline", age: 27, country: "Myanmar", nationality: "Burmese", bloodGroup: "B-" },
    { id: 262, name: "Carter", age: 32, country: "Thailand", nationality: "Thai", bloodGroup: "O+" },
    { id: 263, name: "Scarlett", age: 23, country: "Vietnam", nationality: "Vietnamese", bloodGroup: "A+" },
    { id: 264, name: "Gabriel", age: 29, country: "Cambodia", nationality: "Cambodian", bloodGroup: "AB+" },
    { id: 265, name: "Nora", age: 30, country: "Laos", nationality: "Laotian", bloodGroup: "B+" },
    { id: 266, name: "Wyatt", age: 26, country: "Malaysia", nationality: "Malaysian", bloodGroup: "A-" },
    { id: 267, name: "Lillian", age: 34, country: "Singapore", nationality: "Singaporean", bloodGroup: "O-" },
    { id: 268, name: "Julian", age: 28, country: "Indonesia", nationality: "Indonesian", bloodGroup: "O+" },
    { id: 269, name: "Chloe", age: 30, country: "Philippines", nationality: "Filipino", bloodGroup: "AB-" },
    { id: 270, name: "Eli", age: 25, country: "Taiwan", nationality: "Taiwanese", bloodGroup: "A-" },
    { id: 271, name: "Aurora", age: 33, country: "South Korea", nationality: "South Korean", bloodGroup: "B-" },
    { id: 272, name: "Connor", age: 27, country: "North Korea", nationality: "North Korean", bloodGroup: "O+" },
    { id: 273, name: "Isabel", age: 32, country: "Mongolia", nationality: "Mongolian", bloodGroup: "A+" },
    { id: 274, name: "Felix", age: 23, country: "Kazakhstan", nationality: "Kazakh", bloodGroup: "AB+" },
    { id: 275, name: "Elena", age: 29, country: "Uzbekistan", nationality: "Uzbek", bloodGroup: "B+" },
    { id: 276, name: "David", age: 30, country: "Kyrgyzstan", nationality: "Kyrgyz", bloodGroup: "A-" },
    { id: 277, name: "Sophie", age: 26, country: "Turkmenistan", nationality: "Turkmen", bloodGroup: "O-" },
    { id: 278, name: "Nathaniel", age: 34, country: "Tajikistan", nationality: "Tajik", bloodGroup: "O+" },
    { id: 279, name: "Ivy", age: 28, country: "Azerbaijan", nationality: "Azerbaijani", bloodGroup: "AB-" },
    { id: 280, name: "Dominic", age: 30, country: "Georgia", nationality: "Georgian", bloodGroup: "A-" },
    { id: 281, name: "Julia", age: 25, country: "Armenia", nationality: "Armenian", bloodGroup: "B-" },
    { id: 282, name: "Ryan", age: 33, country: "Cuba", nationality: "Cuban", bloodGroup: "O+" },
    { id: 283, name: "Victoria", age: 27, country: "Haiti", nationality: "Haitian", bloodGroup: "A+" },
    { id: 284, name: "Arthur", age: 32, country: "Jamaica", nationality: "Jamaican", bloodGroup: "AB+" },
    { id: 285, name: "Zoe", age: 23, country: "Trinidad and Tobago", nationality: "Trinidadian", bloodGroup: "B+" },
    { id: 286, name: "Gabriel", age: 29, country: "Mexico", nationality: "Mexican", bloodGroup: "A-" },
    { id: 287, name: "Avery", age: 30, country: "Guatemala", nationality: "Guatemalan", bloodGroup: "O-" },
    { id: 288, name: "Michael", age: 26, country: "Honduras", nationality: "Honduran", bloodGroup: "O+" },
    { id: 289, name: "Ella", age: 34, country: "El Salvador", nationality: "Salvadoran", bloodGroup: "AB-" },
    { id: 290, name: "Samuel", age: 28, country: "Nicaragua", nationality: "Nicaraguan", bloodGroup: "A-" },
    { id: 291, name: "Chloe", age: 30, country: "Costa Rica", nationality: "Costa Rican", bloodGroup: "B-" },
    { id: 292, name: "Benjamin", age: 25, country: "Panama", nationality: "Panamanian", bloodGroup: "O+" },
    { id: 293, name: "Grace", age: 33, country: "Colombia", nationality: "Colombian", bloodGroup: "A+" },
    { id: 294, name: "Daniel", age: 27, country: "Venezuela", nationality: "Venezuelan", bloodGroup: "AB+" },
    { id: 295, name: "Isla", age: 32, country: "Ecuador", nationality: "Ecuadorian", bloodGroup: "B+" },
    { id: 296, name: "Oliver", age: 23, country: "Peru", nationality: "Peruvian", bloodGroup: "A-" },
    { id: 297, name: "Aria", age: 29, country: "Bolivia", nationality: "Bolivian", bloodGroup: "O-" },
    { id: 298, name: "Caleb", age: 30, country: "Chile", nationality: "Chilean", bloodGroup: "O+" },
    { id: 299, name: "Scarlett", age: 26, country: "Argentina", nationality: "Argentinian", bloodGroup: "AB-" },
    { id: 300, name: "Ethan", age: 34, country: "Uruguay", nationality: "Uruguayan", bloodGroup: "A-" },
    { id: 301, name: "Penelope", age: 28, country: "Paraguay", nationality: "Paraguayan", bloodGroup: "B-" },
    { id: 302, name: "Alexander", age: 30, country: "Suriname", nationality: "Surinamese", bloodGroup: "O+" },
    { id: 303, name: "Victoria", age: 25, country: "Guyana", nationality: "Guyanese", bloodGroup: "A+" },
    { id: 304, name: "Sebastian", age: 33, country: "Brazil", nationality: "Brazilian", bloodGroup: "AB+" },
    { id: 305, name: "Hannah", age: 27, country: "Egypt", nationality: "Egyptian", bloodGroup: "B+" },
    { id: 306, name: "Elijah", age: 32, country: "Nigeria", nationality: "Nigerian", bloodGroup: "A-" },
    { id: 307, name: "Mia", age: 23, country: "South Africa", nationality: "South African", bloodGroup: "O-" },
    { id: 308, name: "Jackson", age: 29, country: "Kenya", nationality: "Kenyan", bloodGroup: "O+" },
    { id: 309, name: "Zoe", age: 30, country: "Tanzania", nationality: "Tanzanian", bloodGroup: "AB-" },
    { id: 310, name: "David", age: 26, country: "Uganda", nationality: "Ugandan", bloodGroup: "A-" },
    { id: 311, name: "Nora", age: 34, country: "Ghana", nationality: "Ghanaian", bloodGroup: "B-" },
    { id: 312, name: "Lucas", age: 28, country: "Morocco", nationality: "Moroccan", bloodGroup: "O+" },
    { id: 313, name: "Amelia", age: 30, country: "Algeria", nationality: "Algerian", bloodGroup: "A+" },
    { id: 314, name: "Isaac", age: 25, country: "Tunisia", nationality: "Tunisian", bloodGroup: "AB+" },
    { id: 315, name: "Ella", age: 33, country: "Libya", nationality: "Libyan", bloodGroup: "B+" },
    { id: 316, name: "Julian", age: 27, country: "Chad", nationality: "Chadian", bloodGroup: "A-" },
    { id: 317, name: "Avery", age: 32, country: "Mali", nationality: "Malian", bloodGroup: "O-" },
    { id: 318, name: "Gabriel", age: 23, country: "Niger", nationality: "Nigerien", bloodGroup: "O+" },
    { id: 319, name: "Penelope", age: 29, country: "Mauritania", nationality: "Mauritanian", bloodGroup: "AB-" },
    { id: 320, name: "Miles", age: 30, country: "Senegal", nationality: "Senegalese", bloodGroup: "A-" },
    { id: 321, name: "Chloe", age: 26, country: "Guinea", nationality: "Guinean", bloodGroup: "B-" },
    { id: 322, name: "Wyatt", age: 34, country: "Liberia", nationality: "Liberian", bloodGroup: "O+" },
    { id: 323, name: "Lillian", age: 28, country: "Ivory Coast", nationality: "Ivorian", bloodGroup: "A+" },
    { id: 324, name: "Christian", age: 30, country: "Burkina Faso", nationality: "Burkinabe", bloodGroup: "AB+" },
    { id: 325, name: "Grace", age: 25, country: "Togo", nationality: "Togolese", bloodGroup: "B+" },
    { id: 326, name: "Nathaniel", age: 33, country: "Benin", nationality: "Beninese", bloodGroup: "A-" },
    { id: 327, name: "Ava", age: 27, country: "Cameroon", nationality: "Cameroonian", bloodGroup: "O-" },
    { id: 328, name: "Carter", age: 32, country: "Gabon", nationality: "Gabonese", bloodGroup: "O+" },
    { id: 329, name: "Stella", age: 23, country: "Republic of the Congo", nationality: "Congolese", bloodGroup: "AB-" },
    { id: 330, name: "Julian", age: 29, country: "Democratic Republic of the Congo", nationality: "Congolese", bloodGroup: "A-" },
    { id: 331, name: "Hannah", age: 30, country: "Angola", nationality: "Angolan", bloodGroup: "B-" },
    { id: 332, name: "Leo", age: 26, country: "Zambia", nationality: "Zambian", bloodGroup: "O+" },
    { id: 333, name: "Madeline", age: 34, country: "Zimbabwe", nationality: "Zimbabwean", bloodGroup: "A+" },
    { id: 334, name: "Owen", age: 28, country: "Malawi", nationality: "Malawian", bloodGroup: "AB+" },
    { id: 335, name: "Zoe", age: 30, country: "Mozambique", nationality: "Mozambican", bloodGroup: "B+" },
    { id: 336, name: "Isaac", age: 25, country: "Botswana", nationality: "Botswana", bloodGroup: "A-" },
    { id: 337, name: "Bella", age: 33, country: "Namibia", nationality: "Namibian", bloodGroup: "O-" },
    { id: 338, name: "David", age: 27, country: "Madagascar", nationality: "Malagasy", bloodGroup: "O+" },
    { id: 339, name: "Scarlett", age: 32, country: "Comoros", nationality: "Comoran", bloodGroup: "AB-" },
    { id: 340, name: "Joseph", age: 23, country: "Mauritius", nationality: "Mauritian", bloodGroup: "A-" },
    { id: 341, name: "Avery", age: 29, country: "Seychelles", nationality: "Seychellois", bloodGroup: "B-" },
    { id: 342, name: "Noah", age: 30, country: "Maldives", nationality: "Maldivian", bloodGroup: "O+" },
    { id: 343, name: "Penelope", age: 26, country: "Sri Lanka", nationality: "Sri Lankan", bloodGroup: "A+" },
    { id: 344, name: "Miles", age: 34, country: "Fiji", nationality: "Fijian", bloodGroup: "AB+" },
    { id: 345, name: "Sophia", age: 28, country: "Papua New Guinea", nationality: "Papua New Guinean", bloodGroup: "B+" },
    { id: 346, name: "Oliver", age: 30, country: "Solomon Islands", nationality: "Solomon Islander", bloodGroup: "A-" },
    { id: 347, name: "Grace", age: 25, country: "Vanuatu", nationality: "Vanuatuan", bloodGroup: "O-" },
    { id: 348, name: "Lucas", age: 33, country: "New Caledonia", nationality: "New Caledonian", bloodGroup: "O+" },
    { id: 349, name: "Chloe", age: 27, country: "Tahiti", nationality: "Tahitian", bloodGroup: "AB-" },
    { id: 350, name: "Daniel", age: 32, country: "Samoa", nationality: "Samoan", bloodGroup: "A-" },
    { id: 351, name: "Lily", age: 23, country: "Tonga", nationality: "Tongan", bloodGroup: "B-" },
    { id: 352, name: "Benjamin", age: 29, country: "Kiribati", nationality: "Kiribati", bloodGroup: "O+" },
    { id: 353, name: "Isabel", age: 30, country: "Palau", nationality: "Palauan", bloodGroup: "A+" },
    { id: 354, name: "Jack", age: 26, country: "Marshall Islands", nationality: "Marshallese", bloodGroup: "AB+" },
    { id: 355, name: "Amelia", age: 34, country: "Federated States of Micronesia", nationality: "Micronesian", bloodGroup: "B+" },
    { id: 356, name: "Liam", age: 28, country: "Tuvalu", nationality: "Tuvaluan", bloodGroup: "A-" },
    { id: 357, name: "Madison", age: 30, country: "Nauru", nationality: "Nauruan", bloodGroup: "O-" },
    { id: 358, name: "Wyatt", age: 25, country: "Singapore", nationality: "Singaporean", bloodGroup: "O+" },
    { id: 359, name: "Zoe", age: 33, country: "Malaysia", nationality: "Malaysian", bloodGroup: "AB-" },
    { id: 360, name: "Ethan", age: 27, country: "Indonesia", nationality: "Indonesian", bloodGroup: "A-" },
    { id: 361, name: "Aurora", age: 32, country: "Philippines", nationality: "Filipino", bloodGroup: "B-" },
    { id: 362, name: "Owen", age: 23, country: "Vietnam", nationality: "Vietnamese", bloodGroup: "O+" },
    { id: 363, name: "Penelope", age: 29, country: "Thailand", nationality: "Thai", bloodGroup: "A+" },
    { id: 364, name: "Carter", age: 30, country: "Myanmar", nationality: "Burmese", bloodGroup: "AB+" },
    { id: 365, name: "Chloe", age: 26, country: "Laos", nationality: "Laotian", bloodGroup: "B+" },
    { id: 366, name: "Isaac", age: 34, country: "Cambodia", nationality: "Cambodian", bloodGroup: "A-" },
    { id: 367, name: "Hannah", age: 28, country: "India", nationality: "Indian", bloodGroup: "O-" },
    { id: 368, name: "Oliver", age: 30, country: "Pakistan", nationality: "Pakistani", bloodGroup: "O+" },
    { id: 369, name: "Scarlett", age: 25, country: "Bangladesh", nationality: "Bangladeshi", bloodGroup: "AB-" },
    { id: 370, name: "Gabriel", age: 33, country: "Nepal", nationality: "Nepali", bloodGroup: "A-" },
    { id: 371, name: "Avery", age: 27, country: "Bhutan", nationality: "Bhutanese", bloodGroup: "B-" },
    { id: 372, name: "Jackson", age: 32, country: "Sri Lanka", nationality: "Sri Lankan", bloodGroup: "O+" },
    { id: 373, name: "Victoria", age: 23, country: "Maldives", nationality: "Maldivian", bloodGroup: "A+" },
    { id: 374, name: "Julian", age: 29, country: "Saudi Arabia", nationality: "Saudi", bloodGroup: "AB+" },
    { id: 375, name: "Layla", age: 30, country: "UAE", nationality: "Emirati", bloodGroup: "B+" },
    { id: 376, name: "Thomas", age: 26, country: "Qatar", nationality: "Qatari", bloodGroup: "A-" },
    { id: 377, name: "Natalie", age: 34, country: "Kuwait", nationality: "Kuwaiti", bloodGroup: "O-" },
    { id: 378, name: "Henry", age: 28, country: "Oman", nationality: "Omani", bloodGroup: "O+" },
    { id: 379, name: "Audrey", age: 30, country: "Bahrain", nationality: "Bahraini", bloodGroup: "AB-" },
    { id: 380, name: "Jack", age: 25, country: "Jordan", nationality: "Jordanian", bloodGroup: "A-" },
    { id: 381, name: "Madeline", age: 33, country: "Lebanon", nationality: "Lebanese", bloodGroup: "B-" },
    { id: 382, name: "Miles", age: 27, country: "Syria", nationality: "Syrian", bloodGroup: "O+" },
    { id: 383, name: "Avery", age: 32, country: "Iraq", nationality: "Iraqi", bloodGroup: "A+" },
    { id: 384, name: "Christian", age: 23, country: "Iran", nationality: "Iranian", bloodGroup: "AB+" },
    { id: 385, name: "Bella", age: 29, country: "Afghanistan", nationality: "Afghan", bloodGroup: "B+" },
    { id: 386, name: "Owen", age: 30, country: "Turkey", nationality: "Turkish", bloodGroup: "A-" },
    { id: 387, name: "Sofia", age: 26, country: "Greece", nationality: "Greek", bloodGroup: "O-" },
    { id: 388, name: "William", age: 34, country: "Italy", nationality: "Italian", bloodGroup: "O+" },
    { id: 389, name: "Mia", age: 28, country: "Spain", nationality: "Spanish", bloodGroup: "AB-" },
    { id: 390, name: "James", age: 30, country: "Portugal", nationality: "Portuguese", bloodGroup: "A-" },
    { id: 391, name: "Amelia", age: 25, country: "France", nationality: "French", bloodGroup: "B-" },
    { id: 392, name: "Leo", age: 33, country: "Germany", nationality: "German", bloodGroup: "O+" },
    { id: 393, name: "Ella", age: 27, country: "Netherlands", nationality: "Dutch", bloodGroup: "A+" },
    { id: 394, name: "Benjamin", age: 32, country: "Belgium", nationality: "Belgian", bloodGroup: "AB+" },
    { id: 395, name: "Pranto", age: 23, country: "Switzerland", nationality: "Swiss", bloodGroup: "B+" },
    { id: 396, name: "Jackson", age: 29, country: "Austria", nationality: "Austrian", bloodGroup: "A-" },
    { id: 397, name: "Grace", age: 30, country: "Poland", nationality: "Polish", bloodGroup: "O-" },
    { id: 398, name: "Caleb", age: 26, country: "Czech Republic", nationality: "Czech", bloodGroup: "O+" },
    { id: 399, name: "Lily", age: 34, country: "Hungary", nationality: "Hungarian", bloodGroup: "AB-" },
    { id: 400, name: "Logan", age: 28, country: "Canada", nationality: "Canadian", bloodGroup: "A-" },
];

console.log("New Name ");
let peopleData = [];
for (let people of peoples) {
    // Check if country contains "bangladesh" (case-insensitive)

    if (people.country.toLowerCase().includes("bangladesh")) {
        people.name = "Pranto";
        peopleData.push(people)
        console.log(people.name);
    }
}
console.log(peopleData);














